### ISSUE TITLE
Update documentation (csvw, ...)

### ISSUE THREAD

**Issue by mchlrch** [zazuko/xrm#43]
Update documentation and mapping-examples in the *rdf-mapping-dsl-user* repository. Prepare the content on branch `upcoming`

* [x] explicit `source-types` declaration by the user became unnecessary #42 
* [x] csvw: add separate chapter with specifics for CSVW output
  * null property: #39 
  * optional dialect specification (see also https://github.com/zazuko/rdf-mapping-dsl/issues/10#issuecomment-562867915)
  * ...
* [x] ConstantValueTerm: [airport-mapping.xrm#L15](https://github.com/zazuko/rdf-mapping-dsl/blob/master/runtime-EclipseXtext/airport-mapping/airport-mapping.xrm#L15)
* [x] `rr:sqlQuery` (R2RML views) #29 
* [ ] `rr:parentTriplesMap` #31 
* [ ] Add link to the CHANGELOG in the README
* [x] Mandatory LINE_ENDS in `map` #56 
~* [ ] `RdfPrefixedName` with `:` #12~
* [ ] (some) XML mapping support - [issues](https://github.com/zazuko/rdf-mapping-dsl/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Axml+)
* [x] formatter #10 
* [ ] quickfix for missing classes and properties #1 :octopus: 
* [x] `rr:termType` #30
* [x] specify output format #48 
* [ ] carml extensions #15 #34 
* [x] DatatypeDefinitions inside vocabulary #66 also fix examples to use `xsd:integer`
* [x] remplate re-use replaces `LinkedResourceTerm` #2
